BryantUniversity/BryantUniversity/Models/Major.cs
namespace BryantUniversity.Models
{
    public class Major
    {
        public Major() { }

        public int Id { get; set; }
        public string Title { get; set; }
        public int DepartmentId { get; set; }
        public Department Department { get; set; }
    }
}

BryantUniversity/BryantUniversity/ViewModels/MajorViewModel.cs
using BryantUniversity.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BryantUniversity.ViewModels
{
    public class MajorViewModel
    {
        public IList<Major> Majors { get; set; }
    }
}

BryantUniversity/BryantUniversity/ViewModels/PrereqViewModel.cs
using BryantUniversity.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BryantUniversity.ViewModels
{
    public class PrereqViewModel
    {
        public Course Course { get; set; } 
    }
}

BryantUniversity/BryantUniversity/Controllers/CoursesController.cs
using BryantUniversity.Data;
using BryantUniversity.Models;
using BryantUniversity.Repo;
using BryantUniversity.ViewModels;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Web.Mvc;

namespace BryantUniversity.Controllers
{
    [AllowAnonymous]
    public class CoursesController : Controller
    {
        private Context context;

        public CoursesController()
        {
            context = new Context();
        }

        [HttpGet]
        public ActionResult Index()
        {
            CoursesRepo courseRepo;
            CourseViewModel viewModel;
            IList<Course> courses;
            using (context)
            {
                courseRepo = new CoursesRepo(context);
                viewModel = new CourseViewModel();
                courses = courseRepo.GetAllCourses();
            }

            viewModel.Courses = courses;

            return View("Index", viewModel);
        }

        [HttpGet]
        public ActionResult Prereq(int courseId)
        {
            DepartmentRepo dRepo;
            MajorPreRequisitesRepo reqRepo;
            CoursePreReqViewModel viewModel = new CoursePreReqViewModel();
            using (context)
            {
                dRepo = new DepartmentRepo(context);
                viewModel.PopulateDepermentSelectList(dRepo.GetAllDepartments());
                reqRepo = new MajorPreRequisitesRepo(context);
                viewModel.CoursesAndPreReqs = reqRepo.GetAllMajorPrequisitesForCourse(courseId);
            }

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult AddPreq(int courseId, int departmentId)
        {
            CoursesRepo cRepo;
            CourseViewModel viewModel = new CourseViewModel();
            using (context)
            {
                cRepo = new CoursesRepo(context);
                viewModel.CoursePrereqId = courseId;
                viewModel.Courses = cRepo.GetByDepartment(departmentId);
            }

            return View(viewModel);
        }


        [HttpPost]
        public ActionResult AddPreqPost(int courseId, int prereqId)
        {
            if (courseId == prereqId)
            {
                return View();
            }
            else
            {
                MajorPreRequisitesRepo mprRepo;
                MajorPreRequisite toAdd;
                using (context)
                {
                    mprRepo = new MajorPreRequisitesRepo(context);
                    toAdd = new MajorPreRequisite(prereqId, courseId);
                    mprRepo.Insert(toAdd);
                }

                return View();
            }
        }

        [HttpGet]
        public ActionResult Majors()
        {
            MajorRepo mRepo;
            MajorViewModel viewModel = new MajorViewModel();
            using (context)
            {
                mRepo = new MajorRepo(context);
                viewModel.Majors = mRepo.GetAllMajors();
            }

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Index(CourseViewModel viewModel)
        {
            return View();
        }

        public ActionResult Create()
        {

            var viewModel = new CourseViewModel();
            DepartmentRepo dRepo;
            CourseLevelRepo clRepo;

            using (context)
            {
                dRepo = new DepartmentRepo(context);
                clRepo = new CourseLevelRepo(context);

                viewModel.PopulateDepermentSelectList(dRepo.GetAllDepartments());
                viewModel.PopulateLevelsSelectList(clRepo.GetAllCourseLevels());

            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CourseViewModel formModel)
        {
            using (context)
            {
                CoursesRepo courseRepo = new CoursesRepo(context); ;
                DepartmentRepo dRepo;
                CourseLevelRepo clRepo;
                MajorPreRequisitesRepo mPRepo;

                dRepo = new DepartmentRepo(context);
                clRepo = new CourseLevelRepo(context);
                mPRepo = new MajorPreRequisitesRepo(context);

                if (ModelState.IsValid)
                {
                    if(formModel.Credits <0 || formModel.Credits >4)
                    {
                        ModelState.AddModelError("", "Credits must be a value from 1 - 4");
                        formModel.PopulateDepermentSelectList(dRepo.GetAllDepartments());
                        formModel.PopulateLevelsSelectList(clRepo.GetAllCourseLevels());
                        return View(formModel);
                    }
                    Course doesCoursebyTitleIdExist = courseRepo.GetCourseByCourseTitleId(formModel.CourseTitleId);

                    if (doesCoursebyTitleIdExist != null)
                    {
                        ModelState.AddModelError("", "Course already exists");
                        formModel.PopulateDepermentSelectList(dRepo.GetAllDepartments());
                        formModel.PopulateLevelsSelectList(clRepo.GetAllCourseLevels());
                        formModel.SameTitleId = true;
                        return View(formModel);
                    }
                    else
                    {
                        formModel.PopulateDepermentSelectList(dRepo.GetAllDepartments());
                        formModel.PopulateLevelsSelectList(clRepo.GetAllCourseLevels());
                        try
                        {
                            var course = new Course(formModel.CourseTitleId, formModel.CourseTitle, formModel.Description, formModel.Credits, formModel.CourseLevelId, formModel.DepartmentId);
                            courseRepo.Insert(course);

                            Course cId = courseRepo.GetCourseByCourseTitleId(formModel.CourseTitleId);

                            return RedirectToAction("Index");
                        }
                        catch (DbUpdateException ex)
                        {
                            HandleDbUpdateException(ex);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", "You must fill out all values");
                    formModel.PopulateDepermentSelectList(dRepo.GetAllDepartments());
                    formModel.PopulateLevelsSelectList(clRepo.GetAllCourseLevels());
                    return View(formModel);
                }
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            DepartmentRepo dRepo;
            CourseLevelRepo clRepo;
            CoursesRepo courseRepo;
            CourseViewModel viewModel = new CourseViewModel();
            Course course;

            using (context)
            {
                courseRepo = new CoursesRepo(context);
                dRepo = new DepartmentRepo(context);
                clRepo = new CourseLevelRepo(context);
                viewModel.PopulateDepermentSelectList(dRepo.GetAllDepartments());
                viewModel.PopulateLevelsSelectList(clRepo.GetAllCourseLevels());
                course = courseRepo.GetById(id);
                viewModel.Id = course.Id;
                viewModel.CourseTitleId = course.CourseTitleId;
                viewModel.CourseTitle = course.CourseTitle;
                viewModel.Description = course.Description;
                viewModel.Credits = course.Credits;
                viewModel.CourseLevelId = course.CourseLevelId;
                viewModel.DepartmentId = course.DepartmentId;
            }

            return View("Edit", viewModel);
        }

        [HttpPost]
        public ActionResult Edit(int id, CourseViewModel course)
        {
            DepartmentRepo dRepo;
            CourseLevelRepo clRepo;
            CoursesRepo courseRepo;
            Course newCourse;
            CourseViewModel viewModel = new CourseViewModel();
            using (context)
            {
                courseRepo = new CoursesRepo(context);
                try
                {
                    dRepo = new DepartmentRepo(context);
                    clRepo = new CourseLevelRepo(context);
                    newCourse = new Course(id, course.CourseTitleId, course.CourseTitle, course.Description, course.Credits, course.CourseLevelId, course.DepartmentId);
                    viewModel.PopulateDepermentSelectList(dRepo.GetAllDepartments());
                    viewModel.PopulateLevelsSelectList(clRepo.GetAllCourseLevels());
                    viewModel.Id = id;
                    viewModel.CourseTitle = course.CourseTitle;
                    viewModel.Description = course.Description;
                    viewModel.Credits = course.Credits;
                    viewModel.CourseLevel = course.CourseLevel;
                    viewModel.DepartmentId = course.DepartmentId;
                    courseRepo.Update(newCourse);

                    return RedirectToAction("Index");
                }
                catch (DbUpdateException ex)
                {
                    HandleDbUpdateException(ex);
                    newCourse = null;
                }
            }

            return View("Edit", viewModel);
        }

        [HttpPost]
        public ActionResult DeletePreq(int courseId)
        {
            MajorPreRequisitesRepo mprRepo;

            using (context)
            {
                mprRepo = new MajorPreRequisitesRepo(context);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Assign(int id)
        {
            CoursesRepo cRepo;
            Course viewModel;

            using (context)
            {
                cRepo = new CoursesRepo(context);

BryantUniversity/BryantUniversity/Controllers/MajorsController.cs
using BryantUniversity.Data;
using BryantUniversity.Repo;
using BryantUniversity.ViewModels;
using System.Web.Mvc;

namespace BryantUniversity.Controllers
{
    public class MajorsController : Controller
    {
        private Context context;

        public MajorsController()
        {
            context = new Context();
        }

        public ActionResult Index(int id)
        {
            MajorRequirementsViewModel viewModel = new MajorRequirementsViewModel();
            MajorRequirmentsRepo mRepo;
            using (context)
            {
                mRepo = new MajorRequirmentsRepo(context);
                viewModel.Requirements = mRepo.GetAllMajorRequirementsByMajor(id);

                return View(viewModel);
            }
        }
    }
}

BryantUniversity/BryantUniversity/Views/Courses/AddPreq.cshtml
@model BryantUniversity.ViewModels.CourseViewModel
@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="row">
        <div class="col-md-5">

        </div>
        <div class="col-sm">
            <h2>Add preq from courses in @Model.Courses[0].Department.Name</h2>
        </div>
        <div class="col-md-5">

        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <div class="md-form mt-0">
                <input id="myInput" class="form-control" type="text" placeholder="Search..">
            </div>
        </div>
        <div class="col-sm">

        </div>
        <div class="col-md-3">

        </div>
        <div class="col-sm">

        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <table class="table">
                <thead class="thead-dark">
                    <tr lass="bench-row">
                        <th>CRN</th>
                        <th>Course ID</th>
                        <th>Course Title</th>
                        <th>Description</th>
                        <th>Credits</th>
                        <th>Level</th>
                        <th>Department</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="myTable">
                    @foreach (var course in Model.Courses)
                    {
                        <tr>
                            <td>@course.Id</td>
                            <td>@course.CourseTitleId</td>
                            <td>@course.CourseTitle</td>
                            <td>@course.Description</td>
                            <td>@course.Credits</td>
                            <td>@course.CourseLevel.Level.Value</td>
                            <td>@course.Department.Name</td>
                            <td>
                                @using (Html.BeginForm("AddPreqPost", "courses", new {courseId = Model.CoursePrereqId, prereqId = course.Id}, FormMethod.Post, new { @class = "pure-form pure-form-aligned" }))
                                {
                                    <div class="col-sm">
                                        <button type="submit" class="btn btn-success">Add</button>
                                    </div>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

BryantUniversity/BryantUniversity/Views/Courses/Catalog.cshtml
@model BryantUniversity.ViewModels.CoursePreReqViewModel
@{
    ViewBag.Title = "Catalog";
}


<div class="container">
    <div class="row">
        <div class="col-md-5">

        </div>
        <div class="col-sm">
            <h2>Catalog</h2>
        </div>
        <div class="col-md-5">

        </div>
    </div>
   
       
    @using (Html.BeginForm("Catalog", "Courses", FormMethod.Post, new { @class = "pure-form pure-form-aligned" }))
    {
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="col">
                <input id="myInput" class="form-control" type="text" placeholder="Search..">
            </div>
            <div class="col">
                @Html.LabelFor(model => model.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DropDownListFor(model => model.DepartmentId, Model.DepartmentList, "Department", new { @class = "form-control required", id = "department-list" })
                @Html.ValidationMessageFor(model => model.DepartmentId)

                
            </div>
            <div class="col">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
 
           
        </div>
    }

        <div class="row">
            <div class="col">
                @if(Model.Courses != null)
                { 
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th>Course Id</th>
                            <th>Course Name</th>
                            <th>Description</th>
                            <th>Course Level</th>
                            <th>Department Name</th>
                            <th>Credits</th>
                            <th>Prerequisite</th>

                        </tr>
                    </thead>
                    <tbody id="myTable">
                        @foreach (var course in Model.Courses)
                        {
                            <tr>
                                <td>@course.CourseTitleId</td>
                                <td>@course.CourseTitle</td>
                                <td>@course.Description</td>
                                <td>@course.CourseLevel.Level.Value</td>
                                <td>@course.Department.Name</td>
                                <td>@course.Credits</td>
                                @if(course.CourseMajorPreRequisites.Count > 0)
                                {
                                    foreach(var prereq in course.CourseMajorPreRequisites)
                                    {
                                        if(prereq.PreReq != null)
                                        {
                                            <td>@prereq.PreReq.CourseTitleId</td>
                                        }
                                    }
                                }
                                <td></td>
                            </tr>
                        }
                    </tbody>
                </table>
                }
            </div>
        </div>
</div>

<script src="~/scripts/Schedule.js"></script>
<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

BryantUniversity/BryantUniversity/Views/Courses/Create.cshtml
@model BryantUniversity.ViewModels.CourseViewModel
@{
    ViewBag.Title = "Create";
}

<div class="container">
    <div class="row">
        <div class="col-md-5">
            
        </div>
        <div class="col-sm">
            <h1>Add a course</h1>
        </div>
        <div class="col-md-5">
            
        </div>
    </div>
    <div class="row">
        <div class="col-md-5">

        </div>
        <div class="col-sm">


            @using (Html.BeginForm("Create", "Courses", FormMethod.Post, new { @class = "pure-form pure-form-aligned" }))
            {
                @Html.AntiForgeryToken()

                <fieldset>
                    <div class="pure-controls">
                        @if(Model.SameTitleId)
                        {
                            <h5>A course with this ID already exists</h5>
                        }
                        @Html.LabelFor(model => model.CourseTitleId)
                        @Html.EditorFor(model => model.CourseTitleId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CourseTitleId, "", new { @class = "pure-form-message-inline" })
                    </div>

                    <div class="pure-controls">
                        @Html.LabelFor(model => model.CourseTitle)
                        @Html.EditorFor(model => model.CourseTitle, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CourseTitle, "", new { @class = "pure-form-message-inline" })
                    </div>

                    <div class="pure-controls">
                        @Html.LabelFor(model => model.Description)
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "pure-form-message-inline" })
                    </div>

                    <div class="pure-controls">
                        @Html.LabelFor(model => model.Credits)
                        @Html.EditorFor(model => model.Credits, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Credits, "", new { @class = "pure-form-message-inline" })
                    </div>

                    <div class="pure-controls">
                        @Html.LabelFor(model => model.CourseLevelId, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.DropDownListFor(model => model.CourseLevelId, Model.CourseLevelList, "Course Level", new { @class = "form-control required", id = "period-list" })
                        @Html.ValidationMessageFor(model => model.CourseLevelId)
                    </div>
                    <div class="pure-controls">

                        @Html.LabelFor(model => model.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.DropDownListFor(model => model.DepartmentId, Model.DepartmentList, "Period", new { @class = "form-control required", id = "period-list" })
                        @Html.ValidationMessageFor(model => model.DepartmentId)
                    </div>
                    <div class="pure-controls">
                        @Html.ActionLink("Cancel", "Index", new { }, new { @class = "btn btn-danger" })
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </fieldset>
            }
        </div>
        <div class="col-md-5">

        </div>
    </div>
</div>

BryantUniversity/BryantUniversity/Views/Courses/Delete.cshtml
@model BryantUniversity.ViewModels.CourseDeleteViewModel
@{
    ViewBag.Title = "Delete";
}



<div class="container">
    <div class="row">
        <div class="col-md-5">
            
        </div>
        <div class="col-sm">
            <h2>You Are Trying To Delete @Model.Course.CourseTitle</h2>
        </div>

    </div>


    <div class="row">
        <div class="col-md-5">
            
        </div>
        
        <div class="col-md-5">
            <h4>But You Must Delete The Following Prerequiste(s) first</h4>
        </div>
        
        <div class="col-md-5">
            
        </div>
    </div>
    
    <div class="row">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>Course Id</th>
                    <th>Course Name</th>
                    <th>Description</th>
                    <th>Course Level</th>
                    <th>Department Name</th>
                    <th>Credits</th>
                    <th></th>
                </tr>
            </thead>
            <tbody id="myTable">
                @foreach (var prereqs in Model.Course.CourseMajorPreRequisites)
                {
                    <tr>
                        <td>@prereqs.PreReq.CourseTitleId</td>
                        <td>@prereqs.PreReq.CourseTitle</td>
                        <td>@prereqs.PreReq.Description</td>
                        <td>@prereqs.PreReq.CourseLevel.Level.Value</td>
                        <td>@prereqs.PreReq.Department.Name</td>
                        <td>@prereqs.PreReq.Credits</td>
                        <td>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

BryantUniversity/BryantUniversity/Views/Courses/Edit.cshtml
@model BryantUniversity.ViewModels.CourseViewModel
@{
    ViewBag.Title = "Create";
}

<div class="container">
    <div class="row">
        <div class="col-md-5">

        </div>
        <div class="col-sm">
            <h1>Add a course</h1>
        </div>
        <div class="col-md-5">

        </div>
    </div>
    <div class="row">
        <div class="col-md-5">

        </div>
        <div class="col-sm">


            @using (Html.BeginForm("Edit", "Courses", FormMethod.Post, new { @class = "pure-form pure-form-aligned" }))
            {
                @Html.AntiForgeryToken()

                <fieldset>
                    <div class="pure-controls">
                        @Html.LabelFor(model => model.CourseTitleId)
                        @Html.EditorFor(model => model.CourseTitleId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CourseTitleId, "", new { @class = "pure-form-message-inline" })
                    </div>

                    <div class="pure-controls">
                        @Html.LabelFor(model => model.CourseTitle)
                        @Html.EditorFor(model => model.CourseTitle, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CourseTitle, "", new { @class = "pure-form-message-inline" })
                    </div>

                    <div class="pure-controls">
                        @Html.LabelFor(model => model.Description)
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "pure-form-message-inline" })
                    </div>

                    <div class="pure-controls">
                        @Html.LabelFor(model => model.Credits)
                        @Html.EditorFor(model => model.Credits, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Credits, "", new { @class = "pure-form-message-inline" })
                    </div>

                    <div class="pure-controls">
                        @Html.LabelFor(model => model.CourseLevelId, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.DropDownListFor(model => model.CourseLevelId, Model.CourseLevelList, "Course Level", new { @class = "form-control required", id = "period-list" })
                        @Html.ValidationMessageFor(model => model.CourseLevelId)
                    </div>
                    <div class="pure-controls">

                        @Html.LabelFor(model => model.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.DropDownListFor(model => model.DepartmentId, Model.DepartmentList, "Period", new { @class = "form-control required", id = "period-list" })
                        @Html.ValidationMessageFor(model => model.DepartmentId)
                    </div>
                    <div class="pure-controls">
                        @Html.ActionLink("Cancel", "Index", new { }, new { @class = "btn btn-danger" })
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </fieldset>
            }
        </div>
        <div class="col-md-5">

        </div>
    </div>
</div>

BryantUniversity/BryantUniversity/Views/Courses/Majors.cshtml
@model BryantUniversity.ViewModels.MajorViewModel
@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="row">
        <div class="col-md-5">

        </div>
        <div class="col-sm">
            <h2>All Majors Offered</h2>
        </div>
        <div class="col-md-5">

        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <div class="md-form mt-0">
                <input id="myInput" class="form-control" type="text" placeholder="Search..">
            </div>
        </div>
        <div class="col-sm">

        </div>
        <div class="col-md-3">

        </div>
        <div class="col-sm">

        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <table class="table">
                <thead class="thead-dark">
                    <tr lass="bench-row">
                        <th>Department</th>
                        <th>Major</th>
 
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="myTable">
                    @foreach (var major in Model.Majors)
                    {
                        <tr>
                            <td>@major.Department.Name</td>
                            <td>@major.Title</td>

                            <td>
                                @Html.ActionLink("Requirements", "Index", "Majors", new { id = major.Id }, new { @class = "btn btn-primary" })
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>