BryantUniversity/BryantUniversity/Models/Grade.cs
namespace BryantUniversity.Models
{
    public class Grade
    {
        public Grade() { }

        public Grade(int? gradeId, int registrationId)
        {
            LetterGradeId = gradeId;
            RegistrationId = registrationId;
        }

        public Grade(int id, int? gradeId, int registrationId)
        {
            Id = id;
            LetterGradeId = gradeId;
            RegistrationId = registrationId;
        }

        public int Id { get; set; }
        public int? LetterGradeId { get; set; }
        public LetterGrade LetterGrade { get; set; }
        public int RegistrationId { get; set; }
        public Registration Registration { get; set; }
    }
}

BryantUniversity/BryantUniversity/ViewModels/AssignGradeViewModel.cs
using BryantUniversity.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BryantUniversity.ViewModels
{
    public class AssignGradeViewModel
    {
        public int sectionId { get; set; }
        public User Student { get; set; }
        public CourseSection Section { get; set; }
        public int LetterGradeId { get; set; }
        public IList<LetterGrade> LetterGrades { get; set; }

        public SelectList GradeList
        {
            get
            {
                return new SelectList(LetterGrades, "Id", "GradeVal.Value");
            }
        }


        public void PopulateSelectList(IList<LetterGrade> populatedGrades)
        {
            LetterGrades = populatedGrades;
        }
    }
}

BryantUniversity/BryantUniversity/ViewModels/GradesViewModel.cs
using BryantUniversity.Models;
using System.Collections.Generic;
using System.ComponentModel;
using System.Web.Mvc;

namespace BryantUniversity.ViewModels
{
    public class GradesViewModel
    {
        public GradesViewModel()
        {
            Grades = new List<Grade>();
        }

        public double? CumulativeGpa { get; set; }
        public double? SemesterGpa { get; set; }
        public IList<Grade> Grades { get; set; }
        public IList<Registration> RegisteredClasses { get; set; }
        public SemesterPeriod GradeSemesterPeriod { get; set; }
        [DisplayName("Semester: ")]
        public int PeriodId { get; set; }
        public IList<SemesterPeriod> SemesterPeriods { get; set; }
        public double Gpa { get; set; }
        public SelectList PeriodList
        {
            get
            {
                return new SelectList(SemesterPeriods, "Id", "Period.Value");
            }
        }

        public void PopulateSelectList(IList<SemesterPeriod> populatedPeriods)
        {
            SemesterPeriods = populatedPeriods;

        }
    }
}

BryantUniversity/BryantUniversity/Controllers/GradesController.cs
using BryantUniversity.Data;
using BryantUniversity.Models;
using BryantUniversity.Models.Repo;
using BryantUniversity.Repo;
using BryantUniversity.ViewModels;
using System.Web.Mvc;

namespace BryantUniversity.Controllers
{
    [Authorize(Roles = "2,1")]
    public class GradesController : Controller
    {
        private Context context;

        public GradesController()
        {
            context = new Context();
        }
        // GET: Grades
        [HttpGet]
        public ActionResult AssignGrade(int id, int cid)
        {
            AssignGradeViewModel viewModel = new AssignGradeViewModel();
            UserRepo uRepo;
            LetterGradesRepo lgRepo;
            CourseSectionRepo csRepo;

            using (context)
            {
                csRepo = new CourseSectionRepo(context);
                lgRepo = new LetterGradesRepo(context);
                uRepo = new UserRepo(context);
                User toAssign = uRepo.GetById(id);
                csRepo.GetCourseSectionById(cid);
                viewModel.Section = csRepo.GetCourseSectionById(cid);
                viewModel.PopulateSelectList(lgRepo.GetAllLetterGrades());
                viewModel.Student = toAssign;
            }

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AssignGrade(int id, int cid, AssignGradeViewModel viewModel)
        {

            UserRepo uRepo;
            RegistrationRepo rRepo;
            GradesRepo gRepo;

            using (context)
            {
                rRepo = new RegistrationRepo(context);
                gRepo = new GradesRepo(context);

                rRepo = new RegistrationRepo(context);

                Registration toAssignGrade = rRepo.GetByStudentAndSectionId(id, cid);
                Grade assigned = new Grade(viewModel.LetterGradeId, toAssignGrade.Id);
                gRepo.Insert(assigned);
            }
            return RedirectToAction("Teaching", "Faculty");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            GradesRepo gRepo;

            using (context)
            {
                gRepo = new GradesRepo(context);
                Grade grade = gRepo.GetById(id); 

            }
            return View();
        }
    }
}

BryantUniversity/BryantUniversity/Views/Grades/AssignGrade.cshtml
@model BryantUniversity.ViewModels.AssignGradeViewModel

@{
    ViewBag.Title = "Assign";
}
<div class="container">
    <div class="row">
        <div class="col-sm">

        </div>
        <div class="col-sm">
            Assign final grade
        </div>
        <div class="col-sm">

        </div>
    </div>
    <div class="row">
        <div class="col-sm">

        </div>
        
            <div class="col-sm">
                <h4>Grading available till: @Model.Section.SemesterPeriod.EndGradeTime</h4>
            </div>
        </div>
    <div class="row"></div>
    <div class="row">
        <div class="col-sm">

        </div>
        <div class="col-sm">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th>Student</th>
                        <th>Course Name</th>
                    </tr>
                </thead>
                <tbody id="myTable">

                    <tr>
   
                        <td>@Model.Student.Name</td>
                        <td>@Model.Section.Course.CourseTitleId</td>
                    </tr>

                </tbody>
            </table>

        </div>
        <div class="col-sm">
            @if(DateTime.Now< Model.Section.SemesterPeriod.EndGradeTime)
            { 
                using (Html.BeginForm("AssignGrade", "Grades", new { id = Model.Student.Id, cid = Model.Section.Id}, FormMethod.Post, new { @class = "pure-form pure-form-aligned" }))
                {
                    <div class="row">
                        <div class="col-sm">
                            @Html.LabelFor(model => model.LetterGradeId, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.DropDownListFor(model => model.LetterGradeId, Model.GradeList, "Grade", new { @class = "form-control required", id = "grades-list" })
                            @Html.ValidationMessageFor(model => model.LetterGradeId)
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                        <div class="col-sm">
                            @Html.HiddenFor(model => model.Section)
                        </div>

                        <div class="col-md-5">
                        </div>
                    </div>
                }
            }
            else
            {
                <h4>Grading period has ended</h4>
            }
        </div>
        </div>
    </div>